# Generated by Django 4.0.10 on 2025-08-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='number',
            field=models.IntegerField(default=10, max_length=5),
        ),
    ]
